version: '2.28'

services:
  flask-app:
    image: main_score:03
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:5254"
    volumes:
      - "./scores.txt:/scores.txt"